//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ROIInspector.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_MODTYPE                     129
#define IDI_ROI                         130
#define IDI_LODLIST                     131
#define IDI_LOD                         132
#define IDI_PARTS                       133
#define IDB_PALETTE                     137
#define IDD_SELECT_LODS                 138
#define IDD_ROI_PROP                    140
#define IDD_LOD_PROP                    141
#define IDR_POPUP_MENU1                 142
#define IDD_CONFIGURE_AXIS              143
#define IDD_COSTS                       144
#define IDD_ANIMATE                     145
#define IDC_EDIT1                       1003
#define IDC_EDIT2                       1004
#define IDC_CHECK1                      1005
#define IDC_EDIT3                       1005
#define IDC_ROINAME                     1006
#define IDC_EDIT4                       1006
#define IDC_STATIC2                     1007
#define IDC_EDIT5                       1007
#define IDC_STATIC3                     1008
#define IDC_EDIT6                       1008
#define IDC_STATIC4                     1009
#define IDC_STATIC5                     1010
#define IDC_STATIC6                     1011
#define IDC_STATIC7                     1012
#define IDC_STATIC8                     1013
#define IDC_STATIC9                     1014
#define IDC_STATIC10                    1015
#define IDC_STATIC1                     1016
#define IDC_LIST1                       1017
#define IDC_CHECK3                      1019
#define IDC_COMBO1                      1019
#define IDC_SLIDER1                     1020
#define IDC_MAXTIME                     1021
#define IDC_TIME                        1022
#define ID_VIEW_RESET                   32771
#define ID_VIEW_REMOVEALLBEFOREADDING   32772
#define ID_VIEW_REMOVEALL               32773
#define ID_OPTIONS_VIEW_MULTIPLE_LODS   32776
#define ID_OPTIONS_USESHORTNAMES        32777
#define ID_OPTIONS_BOUNDINGBOX          32778
#define ID_OPTIONS_AXIS                 32779
#define ID_VIEW_LODS                    32780
#define ID_VIEW_ROIPROPERTIES           32781
#define ID_PROPERTIES                   32782
#define ID_TOOLS_CALCULATECOSTS         32783
#define ID_OPTIONS_FIT_IN_WINDOW        32785
#define ID_VIEW_AXIS                    32787
#define ID_OPTIONS_CONFIGURE_AXIS       32789
#define ID_VIEW_LODAXIS                 32791
#define ID_OPTIONS_CONFIGURELODAXIS     32792
#define ID_FILE_OPENANIMATION           32793
#define ID_ANIMATION_OPEN               32794
#define ID_ANIMATION_SETFRAME           32795
#define ID_ANIMATION_SETORIGINAL        32796
#define ID_ANIMATION_ANIMATE            32797

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        147
#define _APS_NEXT_COMMAND_VALUE         32798
#define _APS_NEXT_CONTROL_VALUE         1023
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
