//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Convert.rc
//
#define IDD_CONVERT                     101
#define IDD_MESH                        102
#define IDD_ANIMATION                   103
#define IDD_MODEL                       104
#define IDD_TEXTURE                     105
#define IDI_COMPUTER                    105
#define IDD_OPENMODELDIRECTORY          106
#define IDI_FIXEDDRIVE                  107
#define IDI_CLOSEDFOLDER                108
#define IDI_OPENFOLDER                  109
#define IDI_REMOVABLEDRIVE              110
#define IDI_REMOTEDRIVE                 111
#define IDI_CDROMDRIVE                  112
#define IDD_STUDIOFILE                  113
#define IDD_MODELDIRECTORY              114
#define IDD_SCRIPT                      115
#define IDC_MESHES                      1001
#define IDC_TEXTURES                    1002
#define IDC_ANIMATIONS                  1003
#define IDC_EXIT                        1004
#define IDC_SAVE                        1006
#define IDC_CLOSE                       1007
#define IDC_LIST                        1008
#define IDC_FILE                        1011
#define IDC_DIRECTORY                   1012
#define IDC_MODELS                      1014
#define IDC_TREE                        1017
#define IDC_BROWSE                      1019
#define IDC_SCRIPT                      1021
#define IDC_STUDIOFILE                  1022
#define IDC_MODELDIRECTORY              1023
#define IDC_RUN                         1024

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        116
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1025
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
