/*   
    This unpublished source code contains trade secrets and
    copyrighted materials which are the property of Mindscape, Inc.
    Unauthorized use, copying or distribution is a violation of U.S.
    and international laws and is strictly prohibited.
*/

#ifndef __IDLER_H
#define __IDLER_H

#include <afxwin.h>

class CIdler {
public:
    BOOL Idle(LONG p_counter) { return FALSE; }
};

#endif // __IDLER_H


