//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Lego.rc
//
#define IDD_ABOUTBOX                    100
#define ID_INDICATOR_FRAMERATE          102
#define ID_INDICATOR_FRAMECOUNT         103
#define ID_INDICATOR_RENDERERMEMORY     104
#define ID_INDICATOR_RENDERINGRATE      105
#define IDR_MAINFRAME                   128
#define IDR_LEGOTYPE                    129
#define IDD_REALTIMEVIEW_WEIGHTS        130
#define IDD_REALISM                     131
#define IDB_PALETTE                     133
#define IDC_WEIGHT_FIRST                1008
#define IDC_WEIGHT_SIZE                 1008
#define IDC_WEIGHT_ACCURACY             1009
#define IDC_WEIGHT_SEMANTIC             1010
#define IDC_WEIGHT_FOCUS                1011
#define IDC_WEIGHT_MOTION               1012
#define IDC_WEIGHT_HYSTERESIS           1013
#define IDC_WEIGHT_LAST                 1013
#define IDC_REALISM                     1014
#define IDC_STATIC_WEIGHT_FIRST         1015
#define IDC_STATIC_WEIGHT_SIZE          1015
#define IDC_STATIC_WEIGHT_ACCURACY      1016
#define IDC_STATIC_WEIGHT_SEMANTIC      1017
#define IDC_STATIC_WEIGHT_FOCUS         1018
#define IDC_STATIC_WEIGHT_MOTION        1019
#define IDC_STATIC_WEIGHT_HYSTERESIS    1020
#define IDC_STATIC_WEIGHT_LAST          1020
#define IDC_STATIC_RENDERTIME           1021
#define IDC_BUTTON1                     1022
#define IDC_SENSITIVITY                 1026
#define IDC_SENSITIVITY_TEXT            1027
#define IDC_STATIC_RENDERRATE           1029
#define IDC_STATIC_RENDERRATE_CURRENT   1030
#define IDC_STATIC_RENDERTIME_CURRENT   1031
#define IDC_SLIDER1                     1032
#define ID_FILE_LOAD                    32771
#define ID_EDITOR_CLEAR                 32772
#define ID_EDITOR_REMOVE_ALL            32773
#define ID_EDITOR_LOAD                  32774
#define ID_EDITOR_SELECTPREVIOUS        32775
#define ID_EDITOR_SELECTNEXT            32776
#define ID_EDITOR_REMOVE                32777
#define ID_VIEW_PLAYER                  32778
#define ID_VIEW_EDITOR                  32779
#define ID_VIEW_KIDSEYE                 32780
#define ID_VIEW_CITYPLANNER             32781
#define ID_TOWN_NEWGEOMETRY             32782
#define ID_TOWN_DELETEGEOMETRY          32783
#define IDD_DIALOGS_RVDIALOG            32784
#define ID_VIEW_REALTIMEVIEW_WEIGHTS    32785
#define ID_VIEW_REALISM                 32786
#define ID_VIEW_MESHCOST                32787
#define ID_MESH_CALCULATECOST           32788
#define ID_VIEW_RENDERWHENNOTACTIVE     32789
#define ID_TOWN_LOADMODEL               32790
#define ID_TOWN_LOADPILLARS             32791

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         32792
#define _APS_NEXT_CONTROL_VALUE         1034
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
