//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MeshCost.rc
//
#define IDD_MESHCOST_DIALOG             102
#define IDR_MAINFRAME                   128
#define IDD_PROGRESS                    129
#define IDB_PALETTE                     130
#define IDC_TEST                        1000
#define IDC_FULLSCREEN                  1001
#define IDC_LOAD_MODEL                  1003
#define IDC_SAVE                        1004
#define IDC_CALCULATE_COST              1005
#define IDC_PROGRESS                    1006
#define IDC_PAUSE                       1007
#define IDC_CONTINUE                    1008
#define IDC_ANGLE                       1009
#define IDC_LOD                         1010
#define IDC_ROI                         1011
#define IDC_SIZE2                       1012

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1013
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
