//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by PathDemo.rc
//
#define IDR_MENU                        101
#define IDD_GOTO                        102
#define IDI_DEMO                        103
#define IDD_GETVARIABLE                 104
#define IDD_SETVARIABLE                 105
#define IDD_SETSOUNDVOLUME              106
#define IDD_SETMUSICVOLUME              107
#define IDC_FRAME_NUMBER                1002
#define IDC_ACTION_NAME                 1003
#define IDC_NAME                        1004
#define IDC_VALUE                       1005
#define IDC_SOUNDVOLUME                 1005
#define IDC_MUSICVOLUME                 1006
#define ID_FILE_EXIT                    40001
#define ID_START                        40002
#define ID_STOP                         40003
#define ID_FILE_OPENINTERLEAFFILE       40005
#define ID_FILE_OPENPALETTEFILE         40006
#define ID_COMMANDS_GOTO                40008
#define ID_COMMANDS_GETVARIABLE         40009
#define ID_COMMANDS_SETVARIABLE         40010
#define ID_COMMANDS_SETSOUNDVOLUME      40011
#define ID_COMMANDS_SETMUSICVOLUME      40012

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        106
#define _APS_NEXT_COMMAND_VALUE         40013
#define _APS_NEXT_CONTROL_VALUE         1007
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
